const btnMenuMobile = document.querySelector(".butao-menu-mobile")
const navMenuMobile = document.querySelector(".nav-menu-mobile")
const navMenuDesktop = document.querySelector(".nav-menu-desktop")
const containerApresentacao = document.querySelector(".container-apresentacao")
const setaParaBaixo = document.querySelector(".seta-para-baixo")